%Team 9
%Module 2 Project


%% Import data from text file (This code section generated using Matlab's import functionality)
% Auto-generated by MATLAB on 17-Oct-2019 14:34:39

% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 17);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["schedule_date", "schedule_season", "schedule_week", "schedule_playoff", "team_home", "score_home", "score_away", "team_away", "team_favorite_id", "spread_favorite", "over_under_line", "stadium", "stadium_neutral", "weather_temperature", "weather_wind_mph", "weather_humidity", "weather_detail"];
opts.VariableTypes = ["datetime", "double", "double", "categorical", "categorical", "double", "double", "categorical", "string", "double", "string", "categorical", "categorical", "double", "double", "double", "string"];
opts = setvaropts(opts, 1, "InputFormat", "MM/dd/yyyy");
opts = setvaropts(opts, [9, 11, 17], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [4, 5, 8, 9, 11, 12, 13, 17], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

fn = "/spreadspoke_scores.csv";

% Import the data
game_data = readtable(fn, opts);


%% Clear temporary variables
clear opts

%find(game_data.schedule_season >= 2000)


r = find(game_data.schedule_season<=2010);
filtered = game_data(r,:);
scatter(filtered.schedule_season, filtered.score_home);
